wejscie_marker = createMarker (-1605.59, 710.27, 13.87+1, "arrow", 1.5, 255, 200, 0, 150)
wyjscie_marker = createMarker (1518.91, 1602.02, 10.87+1, "arrow", 1.5, 255, 200, 0, 150)
setElementDimension(wyjscie_marker, 666)
setElementInterior(wyjscie_marker, 112)

addEventHandler("onMarkerHit", wejscie_marker, function(el, md)
    if isPedInVehicle(el) then return end
    fadeCamera(el ,false)
	setElementFrozen(el, true)
	setTimer(function ()
	outputChatBox( "* Wszedłeś(aś) do Komisariatu.", el)
    setElementDimension(el, 666)
    setElementInterior(el, 112)
    setElementPosition(el, 1522.38, 1601.95, 10.87)
	setElementFrozen(el, false)
	showPlayerHudComponent(el, "radar", false)
	fadeCamera(el, true)
	end, 1500, 1)
end)

addEventHandler("onMarkerHit", wyjscie_marker, function(el, md)
    if isPedInVehicle(el) then return end
    fadeCamera(el ,false)
	setElementFrozen(el, true)
	setTimer(function ()
	outputChatBox("* Wyszedłeś(aś) z Komisariatu.", el)
    setElementDimension(el, 0)
    setElementInterior(el, 0)
    setElementPosition(el, -1605.61, 715.19, 12.46)
	setElementFrozen(el, false)
	showPlayerHudComponent(el, "radar", true)
	fadeCamera(el, true)
	end, 1500, 1)
end)